#!/usr/bin/env python3
"""Merge the two standard-rate history sources into the published dataset.

Inputs (both committed to the repo):

  data/history-pre-tedb.json  frozen, hand-verified extract of section VIII
                              ("The evolution of VAT rates applicable in the
                              Member States") of the EC TAXUD booklet
                              vat_rates_en.pdf, last edition 06/2021.
                              Covers 1967 onwards. Never regenerated by CI.

  data/history-tedb.json      produced by backfill_tedb_history.py and kept
                              current by update_history.py. Covers 2016-01-01
                              onwards, which is as far back as TEDB answers.

TEDB wins wherever it has coverage; the booklet supplies everything before
that. Where the two overlap they are compared, and any disagreement is
reported rather than silently resolved.

Usage:
    python3 scripts/build_history.py [--check]

    --check   validate and report only, do not write
"""

import argparse
import datetime as dt
import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
PRE_TEDB_PATH = REPO_ROOT / "data" / "history-pre-tedb.json"
CORRECTIONS_PATH = REPO_ROOT / "data" / "history-corrections.json"
TEDB_PATH = REPO_ROOT / "data" / "history-tedb.json"
RATES_PATH = REPO_ROOT / "data" / "eu-vat-rates-data.json"
OUT_PATH = REPO_ROOT / "data" / "eu-vat-rates-history.json"

# TEDB answers from 2016-01-01, but its 2016 record is flattened: it reports
# Greece at 24% for the whole of 2016, when the rise from 23% only took effect
# on 1 June. The booklet dates that change correctly, so the handover to TEDB
# is set at 2017-01-01, where the two sources agree.
TEDB_EPOCH = dt.date(2016, 1, 1)
HANDOVER = dt.date(2017, 1, 1)
BOOKLET_SOURCE = "ec-taxud-booklet-2021-06"
TEDB_SOURCE = "tedb"

SOURCE_META = {
    BOOKLET_SOURCE: {
        "name": (
            "European Commission, DG TAXUD — "
            "\"VAT rates applied in the Member States of the European Union\", "
            "section VIII \"The evolution of VAT rates applicable in the "
            "Member States\""
        ),
        "edition": "2021-06",
        "url": "https://taxation-customs.ec.europa.eu/system/files/2021-06/vat_rates_en.pdf",
        "note": (
            "Publication discontinued in favour of TEDB. Transcribed once and "
            "frozen; not regenerated automatically."
        ),
    },
    TEDB_SOURCE: {
        "name": "European Commission — Taxes in Europe Database (TEDB)",
        "url": "https://ec.europa.eu/taxation_customs/tedb/",
        "note": (
            "Queried via the VatRetrievalService SOAP endpoint. Returns no "
            "data before 2016-01-01."
        ),
    },
}


def load(path: Path) -> dict:
    if not path.exists():
        sys.exit(f"Missing input: {path.relative_to(REPO_ROOT)}")
    return json.loads(path.read_text(encoding="utf-8"))


def value_of(period: dict):
    """Comparable rate value: a scalar, or a tuple when two standard rates ran
    side by side (Ireland 1983-1985)."""
    if period.get("standard") is not None:
        return period["standard"]
    values = period.get("standard_values")
    return tuple(values) if values else None


def merge_country(
    booklet: list[dict],
    tedb: list[dict],
    corrections: list[dict],
    replace_before: str | None,
    code: str,
    warnings: list[str],
) -> list[dict]:
    early = [p for p in booklet if dt.date.fromisoformat(p["from"]) < HANDOVER]
    early.sort(key=lambda p: p["from"])

    tedb_sorted = sorted(
        (p for p in tedb if dt.date.fromisoformat(p["from"]) >= HANDOVER),
        key=lambda p: p["from"],
    )

    # What TEDB reported at the handover, used to check the join rather than to
    # open a period: a rate already in force is not a change.
    at_handover = next(
        (
            p
            for p in sorted(tedb, key=lambda p: p["from"])
            if dt.date.fromisoformat(p["from"]) < HANDOVER
        ),
        None,
    )
    if at_handover and early and value_of(at_handover) != value_of(early[-1]):
        warnings.append(
            f"{code}: booklet has {value_of(early[-1])}% in force at "
            f"{HANDOVER.isoformat()}, TEDB reports {value_of(at_handover)}% "
            f"— kept the booklet"
        )

    # Cross-check the window both sources cover (handover .. booklet end).
    overlap = [p for p in booklet if dt.date.fromisoformat(p["from"]) >= HANDOVER]
    tedb_by_date = {p["from"]: value_of(p) for p in tedb_sorted}
    for p in overlap:
        if p["from"] not in tedb_by_date:
            warnings.append(
                f"{code}: booklet records a change to {value_of(p)}% on "
                f"{p['from']}, TEDB does not — dropped in favour of TEDB"
            )
        elif tedb_by_date[p["from"]] != value_of(p):
            warnings.append(
                f"{code}: {p['from']} booklet {value_of(p)}% vs TEDB "
                f"{tedb_by_date[p['from']]}% — kept TEDB"
            )

    # A TEDB period that merely restates the rate already running is not a
    # change point; drop it so the timeline reads as changes only.
    if tedb_sorted and early and value_of(tedb_sorted[0]) == value_of(early[-1]):
        tedb_sorted = tedb_sorted[1:]

    periods: list[dict] = []
    for p in early:
        periods.append({**p, "source": BOOKLET_SOURCE})
    for p in tedb_sorted:
        periods.append({**p, "source": TEDB_SOURCE})

    # Hand-entered corrections fill gaps the Commission's sources leave. They
    # win on their own dates and are never overwritten by a generated period.
    # `replace_before` additionally drops the generated periods a national
    # source contradicts outright, rather than interleaving both accounts.
    if replace_before:
        dropped = [p for p in periods if p["from"] < replace_before]
        periods = [p for p in periods if p["from"] >= replace_before]
        if dropped:
            warnings.append(
                f"{code}: replaced {len(dropped)} period(s) before "
                f"{replace_before} with hand-entered national-source data"
            )
    if corrections:
        corrected_dates = {p["from"] for p in corrections}
        periods = [p for p in periods if p["from"] not in corrected_dates]
        periods.extend(corrections)

    periods.sort(key=lambda p: p["from"])

    # A correction can restate the rate already running on its far side (the
    # period reopened after a temporary change). Collapse those.
    deduped: list[dict] = []
    for period in periods:
        if deduped and value_of(deduped[-1]) == value_of(period):
            continue
        deduped.append(period)
    periods = deduped

    # Close each period the day before the next one opens.
    for i, period in enumerate(periods):
        if i + 1 < len(periods):
            next_start = dt.date.fromisoformat(periods[i + 1]["from"])
            period["to"] = (next_start - dt.timedelta(days=1)).isoformat()
        else:
            period["to"] = None

    return periods


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()

    booklet_data = load(PRE_TEDB_PATH)["periods"]
    tedb_data = load(TEDB_PATH)["periods"]
    corrections_file = load(CORRECTIONS_PATH)
    corrections_data = corrections_file["periods"]
    replace_before = corrections_file.get("replace_before", {})
    rates = load(RATES_PATH)["rates"]

    sources = {**SOURCE_META, **corrections_file.get("sources", {})}

    warnings: list[str] = []
    history: dict[str, dict] = {}

    for code in sorted(set(booklet_data) | set(tedb_data)):
        periods = merge_country(
            booklet_data.get(code, []),
            tedb_data.get(code, []),
            corrections_data.get(code, []),
            replace_before.get(code),
            code,
            warnings,
        )
        if not periods:
            warnings.append(f"{code}: no periods from either source")
            continue
        history[code] = {
            "country": rates.get(code, {}).get("country", code),
            "periods": periods,
        }

    # EU law puts a 15% floor under the standard rate. Only check from Croatia's
    # accession onwards, after which every country here was a member — earlier,
    # candidate states legitimately ran lower rates (Cyprus at 8% in 1993).
    for code, entry in history.items():
        for period in entry["periods"]:
            value = period.get("standard")
            if value is None or period["from"] < "2013-07-01":
                continue
            if value < 15:
                warnings.append(
                    f"{code}: implausible standard rate {value}% from "
                    f"{period['from']} — check for a territorial rate in the "
                    f"STANDARD slot"
                )

    for line in warnings:
        print(f"warning: {line}", file=sys.stderr)

    total = sum(len(v["periods"]) for v in history.values())
    print(
        f"{len(history)} member states, {total} periods, "
        f"{len(warnings)} warnings",
        file=sys.stderr,
    )

    if args.check:
        return

    payload = {
        "version": dt.date.today().isoformat(),
        "rate_type": "standard",
        "publisher": {"name": "vatnode.dev", "url": "https://vatnode.dev"},
        "coverage": {
            "from": min(
                p["from"] for v in history.values() for p in v["periods"]
            ),
            "tedb_from": HANDOVER.isoformat(),
        },
        "sources": sources,
        "history": history,
    }
    OUT_PATH.write_text(
        json.dumps(payload, ensure_ascii=False, indent=2) + "\n", encoding="utf-8"
    )
    print(f"Wrote {OUT_PATH.relative_to(REPO_ROOT)}", file=sys.stderr)


if __name__ == "__main__":
    main()
